from __future__ import annotations

import datetime
from pathlib import Path

from litsearch.config import Config
from litsearch.pubmed import Paper
from litsearch.scoring import _author_matches


def render_report(
    papers: list[Paper],
    cfg: Config,
    start_date: str,
    end_date: str,
    version: str = "0.1.0",
) -> str:
    def esc(s: str) -> str:
        return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace('"', "&quot;")

    sections: dict[str, list[Paper]] = {}
    for p in papers:
        group = p.matched_groups[0] if p.matched_groups else "Other"
        sections.setdefault(group, []).append(p)

    paper_badges: dict[str, list[dict]] = {}
    for p in papers:
        badges = []
        for author in cfg.authors:
            if _author_matches(author, p.authors):
                display = author.name.split(",")[0].strip() if "," in author.name else author.name.split()[-1]
                badges.append({"name": display, "priority": author.priority})
        if badges:
            paper_badges[p.pmid] = badges

    date_str = f"{start_date} to {end_date}" if start_date != end_date else end_date
    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M UTC")
    cwd = Path.cwd()
    try:
        cwd_display = "~/" + str(cwd.relative_to(Path.home()))
    except ValueError:
        cwd_display = cwd.name

    parts = [
        "<!DOCTYPE html>",
        "<html lang='en'>",
        "<head>",
        "<meta charset='UTF-8'>",
        "<meta name='viewport' content='width=device-width, initial-scale=1.0'>",
        f"<title>litsearch Report — {esc(date_str)}</title>",
        "<!-- <link rel='stylesheet' href='litsearch.css'> -->",
        "</head>",
        "<body>",
        f"<h1>litsearch Report</h1>",
        f"<p class='meta'>{esc(date_str)} &middot; {esc(cwd_display)} &middot; {len(papers)} papers &middot; PubMed</p>",
    ]

    # Summary
    parts.append("<ul class='summary'>")
    for group, ps in sorted(sections.items()):
        parts.append(f"<li>{esc(group)}: {len(ps)}</li>")
    parts.append("</ul>")

    # Sections
    for section_name, section_papers in sections.items():
        parts.append(f"<section class='section'>")
        parts.append(f"<h2>{esc(section_name)} <span class='count'>({len(section_papers)})</span></h2>")
        parts.append("<ul class='papers'>")
        for paper in section_papers:
            meta_parts = [esc(paper.journal)]
            if paper.pub_date:
                meta_parts.append(esc(paper.pub_date))
            if paper.doi:
                meta_parts.append(f"DOI: {esc(paper.doi)}")

            parts.append("<li class='paper'>")
            parts.append(f"<h3><a href='{esc(paper.url)}' target='_blank' rel='noopener'>{esc(paper.title)}</a></h3>")
            parts.append(f"<p class='meta'>{' &middot; '.join(meta_parts)}</p>")

            badges = paper_badges.get(paper.pmid, [])
            if badges:
                badges_html = " ".join(
                    f"<span class='badge badge-{b['priority']}'>{esc(b['name'])}</span>"
                    for b in badges
                )
                parts.append(f"<p class='badges'>{badges_html}</p>")

            parts.append(f"<p class='score'>Score: {paper.relevance_score:.1f}</p>")

            if paper.relevance_reason:
                parts.append(f"<p class='reason'>{esc(paper.relevance_reason)}</p>")

            if paper.abstract:
                abs_text = paper.abstract[:1000] + ("..." if len(paper.abstract) > 1000 else "")
                parts.append("<details><summary>Abstract</summary>")
                parts.append(f"<p class='abstract'>{esc(abs_text)}</p>")
                parts.append("</details>")

            parts.append("</li>")
        parts.append("</ul>")
        parts.append("</section>")

    if not sections:
        parts.append("<p class='empty'>No papers matched your keyword profile for this date range.</p>")

    parts.append(f"<footer>Generated by litsearch v{esc(version)} &middot; {now}</footer>")
    parts.append("</body></html>")

    return "\n".join(parts)
